### ISSUE TITLE
ERROR: empty stream is not considered valid

### ISSUE THREAD

**Issue by mboratko** [AmesCornish/buttersink#36]
The send operation completed, but then it failed with the error above. Here's the full output from the operation:

```
  Optimal synchronization:
  16.16 GiB from 27 diffs in btrfs /srv/nfs4/main/snapshots
  16.16 GiB from 27 diffs in TOTAL
  Xfer: 2a29...de86 /srv/nfs4/main/snapshots/monthly.11 from None (5.262 GiB)
 0:03:08.499894: Sent 5.225 GiB of 5.262 GiB (99%) ETA: 0:00:01.338814 (238 Mbps )                     
  btrfs receive errors
At subvol monthly.11
ERROR: empty stream is not considered valid
  ERROR: receive /mnt/backups/monthly.11 returned error 1..
```

Here's the relevant end from the log:

```
2017-01-27 21:15:46,512:    INFO:buttersink.py[245]: Optimal synchronization:
2017-01-27 21:15:46,512:    INFO:buttersink.py[250]: 16.16 GiB from 27 diffs in btrfs /srv/nfs4/main/snapshots
2017-01-27 21:15:46,513:    INFO:buttersink.py[250]: 16.16 GiB from 27 diffs in TOTAL
2017-01-27 21:15:46,513:    INFO:Store.py[343]: Xfer: 2a29...de86 /srv/nfs4/main/snapshots/monthly.11 from None (5.262 GiB)
2017-01-27 21:15:48,586:   DEBUG:Store.py[124]: [u'monthly.11']
2017-01-27 21:15:48,586:   DEBUG:Butter.py[87]: Command: ['btrfs', 'receive', '-e', u'/mnt/backups']
2017-01-27 21:15:50,592:   DEBUG:Butter.py[110]: Command: ['btrfs', 'send', u'/srv/nfs4/main/snapshots/monthly.11']
2017-01-27 21:15:51,246:   DEBUG:send.py[180]: Setting received 2a29abae-fa50-8b44-8ee3-e0b907b2de86/32890 and parent None/0
2017-01-27 21:15:51,261:   DEBUG:send.py[190]: Version: 1
2017-01-27 21:15:51,261:   DEBUG:send.py[198]: Command: 1
2017-01-27 21:15:51,261:   DEBUG:send.py[268]: Subvol: 2a29abae-fa50-8b44-8ee3-e0b907b2de86/32890 monthly.11
2017-01-27 21:15:51,263:   DEBUG:send.py[180]: Setting received 2a29abae-fa50-8b44-8ee3-e0b907b2de86/32890 and parent None/0
2017-01-27 21:15:51,272:   DEBUG:send.py[190]: Version: 1
2017-01-27 21:15:51,272:   DEBUG:send.py[198]: Command: 1
2017-01-27 21:15:51,273:   DEBUG:send.py[268]: Subvol: 2a29abae-fa50-8b44-8ee3-e0b907b2de86/32890 monthly.11
2017-01-27 21:18:59,095:   DEBUG:Butter.py[226]: Waiting for send process to finish...
2017-01-27 21:18:59,096:   DEBUG:Butter.py[147]: Waiting for receive process to finish...
2017-01-27 21:18:59,103:   ERROR:Butter.py[161]: btrfs receive errors
2017-01-27 21:18:59,103:   DEBUG:Butter.py[174]: Renamed /mnt/backups/monthly.11 to /mnt/backups/monthly.11_2017-01-27T21:18:59.103487.part
2017-01-27 21:18:59,104:   DEBUG:buttersink.py[274]: Trace information for debugging
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/buttersink/buttersink.py", line 257, in main
    diff.sendTo(dest, chunkSize=args.part_size << 20)
  File "/usr/local/lib/python2.7/dist-packages/buttersink/Store.py", line 354, in sendTo
    transfer(sendContext, receiveContext, chunkSize)
  File "/usr/local/lib/python2.7/dist-packages/buttersink/Store.py", line 276, in transfer
    writer.write(data)
  File "/usr/local/lib/python2.7/dist-packages/buttersink/Butter.py", line 179, in __exit__
    % (self.path, self.process.returncode, )
Exception: receive /mnt/backups/monthly.11 returned error 1.
2017-01-27 21:18:59,106:   ERROR:buttersink.py[275]: ERROR: receive /mnt/backups/monthly.11 returned error 1..
```

I'm not sure if it completely transferred, as there is a slight discrepancy in size.

Here's the original:

```
sudo btrfs fi du -s monthly.11
     Total   Exclusive  Set shared  Filename
   5.21GiB       0.00B     5.21GiB  monthly.11
```

Here's what was transferred:
```
sudo btrfs fi du -s monthly.11_2017-01-27T21:18:59.103487.part
     Total   Exclusive  Set shared  Filename
   5.19GiB     5.19GiB       0.00B  monthly.11_2017-01-27T21:18:59.103487.part
```
I am using kernel 4.8.0 with btrfs-progs 4.9 on Debian Stable.

**Comment by ndp34** [comment]
same issue here :(, but this seems btrfs receive related bug

**Comment by AmesCornish** [comment]
I also think this is a btrfs issue.  Make sure you have the latest btrfs-progs.  It also sometimes helps to refresh quotas:
`sudo btrfs quota disable <path>`
`sudo btrfs quota enable <path>`

**Comment by DonOregano** [comment]
Same issue here. Quota trick did not help.
I am running Arch, so these are my versions:
core/btrfs-progs 4.10.2-1
kernel 4.10.13-1-ARCH

**Comment by DonOregano** [comment]
It appears to be fixed in git https://bugzilla.kernel.org/show_bug.cgi?id=195597.
I built btrfs-progs-git, and now it is working for me. YMMV.
